-- Add missing columns to Booking table
ALTER TABLE Booking 
ADD COLUMN startDate DATE AFTER tourId,
ADD COLUMN endDate DATE AFTER startDate,
ADD COLUMN numberOfBaby INT DEFAULT 0 AFTER numberOfChild,
ADD COLUMN fullName VARCHAR(255) AFTER status,
ADD COLUMN email VARCHAR(255) AFTER fullName,
ADD COLUMN phone VARCHAR(20) AFTER email,
ADD COLUMN address TEXT AFTER phone,
ADD COLUMN note TEXT AFTER address,
ADD COLUMN paymentMethod ENUM('card', 'bank', 'cash') AFTER note,
ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER paymentMethod,
ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER createdAt;
