ALTER TABLE Post ADD COLUMN description TEXT AFTER title;
ALTER TABLE Post ADD COLUMN thumbnailUrl VARCHAR(255) AFTER description;
ALTER TABLE Post ADD COLUMN location VARCHAR(255) AFTER thumbnailUrl;
ALTER TABLE Post ADD COLUMN readTime INT AFTER location;
ALTER TABLE Post ADD COLUMN updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER createdAt;

ALTER TABLE Comment ADD COLUMN postId INT AFTER tourId;
ALTER TABLE Comment ADD CONSTRAINT fk_comment_post FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE CASCADE;